---
title: "Replication of 'Are Older Adults More Willing to Donate? The Roles of Donation Form and Social Relationship' by Gong, Zhang & Fung (2019, The Journals of Gerontology: Series B)"
author: "Raphael Uricher (Email: ruricher@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

My research interests lie broadly in culture, emotion, and well-being, topics that may not appear to be directly related to this study at first glance. However, the complex interplay between age, donation behaviour, and various relational factors (i.e., kinship, social distance) described in the original paper intuitively appears to me to be shaped by culture. Culture moulds how we understand age, our attitudes towards donation, and -- perhaps most importantly here -- how we relate to our families and close others (vs our non-relatives and strangers). When I looked over the original paper, I was interested to see that the sample was composed of "community-dwelling Chinese adults" apparently living in Hong Kong and immediately wondered if possible cultural differences between the sample used in original study and the sample used in the first replication attempt may have been implicated in the failure to replicate. Indeed, the authors of the original paper suggest the possibility of culture influencing their results, writing that "future studies should test whether this age difference in kin-selection in prosocial behaviors varies across cultures". If possible within the constraints of this project, I would be interested in potentially controlling for cultural background in my replication attempt, but I am very interested in this project in any case.

To conduct this experiment, I will need to collect data from a sample of older and younger adults. I will need to create a survey containing the following demographic items: gender, age, core social network size (i.e., estimated number of important relatives/friends), level of education, and household income. Older participants will also be asked to complete the Alzheimer’s Disease Assessment Scale-Cognitive Subscale (ADAS-Cog) as a measure of cognitive function. All participants will be asked to complete a hypothetical donation task in they will be asked how much money or time they would donate to a number of targets who systematically vary in their closeness to and kinship with the participant. The study will use a mixed design in which age (older vs younger) is a between-subjects variable and donation form (money vs time), kinship with the target (relative vs non-relative), and social distance with the target (targets ranked 1st, 2nd, 5th, 10th, 20th, 50th, and 100th in a list of 100 people ranked in descending order of closeness) are within-subjects variables.

Analysis will involve first fitting a hyperbolic discount function to group data and testing for goodness of fit, then fitting a hyperbolic discount function to individual data to find each participant's discount rate (k) and area under curve (AUC) values. k and AUC values will then be log-transformed. Correlations between demographic variables and transformed k and AUC values will be investigated, and finally I will run a mixed 2 (age) × 2 (donation form) × 2 (kinship) repeated measures ANOVA on transformed k and AUC values.

A key challenge will be recruitment of a sample of older adults. The older adult sample in the original study were 60-84 years old and it may be difficult to recruit people in this age bracket through Prolific. It may be worthwhile considering a) not including the older adult sample, b) the benefits and pitfalls of recruiting a slightly younger older adult sample, c) whether it might be possible to include age as a continuous rather than categorical variable and changing the analysis strategy accordingly, or d) including age as a control variable rather than as an independent variable of primary interest. A personal challenge will be learning how to fit a function to data; this is something I've never done before but a skill I'm looking forward to developing.

[Github Repository](https://github.com/psych251/gong2019_rescue)

[Original Paper](https://github.com/psych251/gong2019_rescue/blob/main/original_paper/gbx099.pdf)
