---
title: "Replication of 'Are Older Adults More Willing to Donate? The Roles of Donation Form and Social Relationship' by Gong, Zhang & Fung (2019, The Journals of Gerontology: Series B)"
author: "Raphael Uricher (Email: ruricher@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

My research interests lie broadly in culture, emotion, and well-being, topics that may not appear to be directly related to this study at first glance. However, the complex interplay between age, donation behaviour, and various relational factors (i.e., kinship, social distance) described in the original paper intuitively appears to me to be shaped by culture. Culture moulds how we understand age, our attitudes towards donation, and -- perhaps most importantly here -- how we relate to our families and close others (vs our non-relatives and strangers). When I looked over the original paper, I was interested to see that the sample was composed of "community-dwelling Chinese adults" apparently living in Hong Kong and immediately wondered if possible cultural differences between the sample used in original study and the sample used in the first replication attempt may have been implicated in the failure to replicate. Indeed, the authors of the original paper suggest the possibility of culture influencing their results, writing that "future studies should test whether this age difference in kin-selection in prosocial behaviors varies across cultures". If possible within the constraints of this project, I would be interested in potentially controlling for cultural background in my replication attempt, but I am very interested in this project in any case.

To conduct this experiment, I will need to collect data from a sample of older and younger adults. I will need to create a survey containing the following demographic items: gender, age, core social network size (i.e., estimated number of important relatives/friends), level of education, and household income. Older participants will also be asked to complete the Alzheimer’s Disease Assessment Scale-Cognitive Subscale (ADAS-Cog) as a measure of cognitive function. All participants will be asked to complete a hypothetical donation task in they will be asked how much money or time they would donate to a number of targets who systematically vary in their closeness to and kinship with the participant. The study will use a mixed design in which age (older vs younger) is a between-subjects variable and donation form (money vs time), kinship with the target (relative vs non-relative), and social distance with the target (targets ranked 1st, 2nd, 5th, 10th, 20th, 50th, and 100th in a list of 100 people ranked in descending order of closeness) are within-subjects variables.

Analysis will involve first fitting a hyperbolic discount function to group data and testing for goodness of fit, then fitting a hyperbolic discount function to individual data to find each participant's discount rate (k) and area under curve (AUC) values. k and AUC values will then be log-transformed. Correlations between demographic variables and transformed k and AUC values will be investigated, and finally I will run a mixed 2 (age) × 2 (donation form) × 2 (kinship) repeated measures ANOVA on transformed k and AUC values.

A key challenge will be recruitment of a sample of older adults. The older adult sample in the original study were 60-84 years old and it may be difficult to recruit people in this age bracket through Prolific. It may be worthwhile considering a) not including the older adult sample, b) the benefits and pitfalls of recruiting a slightly younger older adult sample, c) whether it might be possible to include age as a continuous rather than categorical variable and changing the analysis strategy accordingly, or d) including age as a control variable rather than as an independent variable of primary interest. A personal challenge will be learning how to fit a function to data; this is something I've never done before but a skill I'm looking forward to developing.

[Github Repository](https://github.com/psych251/gong2019_rescue)

[Original Paper](https://github.com/psych251/gong2019_rescue/blob/main/original_paper/gbx099.pdf)

## Summary of prior replication attempt

The prior replication attempt was conducted by Yochai Shavit in 2017 and was unable to replicate Gong et al.'s (2019) main findings. However,  Shavit's replication attempt departed from the original study on a number of dimensions. Firstly, the original sample consisted of 89 younger (age range: 18-44, mean: 30.1) and 66 older adults (age range: 60-84, mean: 69.4) from Hong Kong. In the replication attempt, based on a power analysis indicating that data from 45 younger and 45 older adults would be sufficient to detect a main effect of age with 80% power in a one-tailed t-test, 43 younger (age range: 19-35, mean: 28.2) and 47 older (age range: 57-74, mean: 62.7) adults living in the United States were recruited. The samples thus differed in three key ways: the sample in the replication study was smaller, the participants in the replication study were younger, and the samples represented two very different cultures. Of these, Shavit suggests - and I concur - that the factor likely to be most implicated in the failure to replicate is culture, given there are different norms surrounding donation and attitudes towards relatives in Hong Kong and the United States. Additional differences in implementation and analysis were as follows:

1) The original study was conducted in person in a lab, whereas the replication study was conducted online. Given the study's variables essentially consist exclusively of a survey, this seems unlikely to have caused any issues.

2) Participants in the original study were asked to imagine they had 100,000 Hong Kong dollars (HKD), whereas participants in the replication study were asked to imagine they had 100,000 US dollars (USD) to fit the context in which the data was collected. 100,000 HKD is approximately equivalent to 13,000 USD. Shavit consulted the first author of the original study about how to reconcile this discrepancy and was told to instruct participants to imagine having 100,000 USD rather than an amount equivalent to 100,000 HKD. Because this study focuses on how much participants are relatively willing to donate to others as a function of how close they are and whether they are related to them, rather than the absolute amount they are willing to donate, I feel there should be minimal issues with this approach.

3) In the original study, older participants' cognitive function was assessed using the cognitive subscale of the Alzheimers' Disease Assessment Scale (ADAS-Cog) to ensure the results would not be confounded with cognitive function. Because this is not a computer-based test, it was not used in the replication study. This seems unlikely to have been an issue because, in the original study, cognitive function and willingness to donate were not significantly correlated.

4) Because the replication study was conducted online, Shavit included a simple attention check and excluded participants who failed it.

5) The authors of the original study fit the hyperbolic discount function to the data using Matlab, but Shavit did this using the “optim” function from the ‘stats’ package in R. Shavit was able to obtain similar results to the original authors when testing this procedure a priori using simulated data, suggesting that differences in the results were not an artefact of different software being used for analysis.

6) The authors of the original study did not report how they dealt with missing data. In the replication study, Shavit excluded participants with missing AUC values from analysis.

7) In the original study, the younger adult group was comprised of participants aged between 18 and 44. Shavit elected to collect data from participants aged between 18 and 35. Additionally, the youngest participant/s in the older adult group in the original study was/were 60, but the youngest participant/s in the older adult group in the replication study was/were 57 because of constraints with regard to participant screening on Mechanical Turk.

8) The authors of the original study did not report using any post-hoc correction when conducting t-tests. In the replication study, Shavit reported the results of t-tests both with and without Bonferroni correction.


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

How much power does your planned sample have for original effect? For an attenuated effect that is half the size of the original? 

(If power analysis is not possible or precise, discuss more fully how you determined a sample size that would be sufficient for rescue.)

### Planned Sample

Planned sample size will be based on power analysis. I will collect data from both a younger sample (aged between 18 and 44, following the original study) and an older sample (aged above 60, following the original study). The author of the replication study suggested that cultural differences may have driven the failure to replicate. I will not be able to collect data specifically from Hong Kong Chinese participants as in the original study due to a dearth of Hong Kong residents actively using Prolific, but one option may be to recruit participants who identify as Asian and/or list a Chinese language (e.g., Mandarin, Cantonese) as their first language to try to sample people with more similar cultural backgrounds to the participants in the original study than those who participated in the first replication attempt. 

### Materials

Participants will be asked to list their gender, age, level of education, and household income. As a measure of core social network size, participants will be asked to estimate the number of important friends and family they have in their lives. 

Participants will then be asked to complete hypothetical donation tasks for both relatives and non-relatives. The initial instruction will be as follows: “The following task asks you to imagine that you have a list of 100 relatives (non-relatives) arranged in descending order of their closeness with you. The person at position #1 is your closest relative (non-relative), while the person at position #100 is a relative (non-relative) you may know but are not close at all. You do not have to actually create the list – just imagine that you have done so. Next you will be asked to answer questions regarding these relatives (non-relatives) at a given position.”

Participants will then be asked 14 questions regarding how much money and time they would be willing to donate to the relatives and non-relatives at each of the following positions on those lists: 1st, 2nd, 5th, 10th, 20th, 50th, and 100th. The questions will read as follows: “Imagine that the relative (non-relative) at position N on your list is now hospitalized. He/she needs to be accompanied and taken care of in the hospital, as well as a large amount of money to pay for the medical expense. If you now own 100 thousand of US dollars and 100 days of vacation, how much money would you donate to him/her, and how many days would you spend taking care of him/her?”

The only difference between the materials described here and those used in the original study is that participants will be asked to imagine they have 100,000 US dollars rather than 10,000 HK dollars, following the instructions given to the author of the first replication attempt from the first author of the original study.

### Procedure	

Participants will be asked to complete a Qualtrics survey containing the measures described above in the order they appear above.

### Controls

Following the first replication attempt, I will include a simple attention check. After participants are asked how much time and money they would be willing to donate to a relative at position 20 on their list, they will also be asked the following question: “In the last question, your answers referred to the participant in position:” with 3, 7, 12, 16, 20, 28, and 42 as answer choices. Participants who do not answer '20' will be excluded from analysis.

### Analysis Plan

Firstly, identifiable information will be removed from the data set. Next, I will follow the analysis plan outlined in the original study:

>To analyze the donation data, we first modeled the group donation data. For each age × donation form × kinship cell, a hyperbolic discount function (i.e., Equation 1) was fit to the group median values (Jones & Rachlin, 2006; Rachlin & Jones, 2007, 2008) over the seven social distances (N = 1, 2, 5, 10, 20, 50, and 100): $$v=V/(1+kN)$$ where V is the undiscounted reward value, v is the reward value that a person would like to forgo for the benefit for someone at a social distance N, and k is a constant indexing degree of social discounting (i.e., discount rate) across social distances. Following the convention of the literature, group median values instead of mean values were used because such data were usually not normally distributed (e.g., Jones & Rachlin, 2006).

>The fitting process was conducted by curve fit toolbox of Matlab (version 2015a), where R-square and root-mean-square error (RMSE) were used to assess the goodness of fit. Such a modeling technique has been widely used in the literature on temporal (e.g., Frederick, Loewenstein, & O’Donoghue, 2002) and social discounting (e.g., Jones & Rachlin, 2006). The technique enables us to sketch individuals’ donation willingness across various social distances with simple parameters like discount rate (k) and area under curve (AUC) (e.g., Jones & Rachlin, 2006; Margittai et al., 2015). Discount rate (k) reflects a donor’s social-distance dependent selectivity as to donation willingness—a larger k value indicates a higher level of selectivity, that is, the donor treats socially close and distant recipients more differently. AUC could be used to index the donor’s overall generosity to people independent of social distance, with a larger value indicating a higher level of generosity (Margittai et al., 2015; Strombach et al., 2014).

>Once the appropriateness of the hyperbolic discount function was confirmed for group data, we then conducted the same fitting process to individual data to get the discount rate (k) and the AUC for each participant under different conditions. Again following the convention of the literature, individual data that did not fit the hyperbolic discount function were excluded from further analyses (Vuchinich & Simpson, 1998). The individuals’ k and AUC values were then normalized by a natural logarithm transformation (e.g., Margittai et al., 2015), and transformed values that exceeded ±3 SDs were treated as outliers.

>Next, the transformed individual k and AUC values were correlated with demographic variables to preliminarily check the influences of demographic variables on donation willingness. To examine the moderating roles of donation form and kinship in the relation between age and donation willingness, the transformed individual AUC values and k values were submitted respectively to a 2 (age: younger and older) × 2 (donation form: money and time) × 2 (kinship: relatives and nonrelatives) mixed design, repeated measures ANOVA (and post hoc tests), with and without controlling for demographic variables.

I will depart from the above analysis plan only in that I will use R rather than Matlab to conduct curve fitting and analyse data. Additionally, as in the first replication attempt, I will report the results of t-tests both with and without applying Bonferroni correction.

The key analysis of interest is the mixed design, repeated measures ANOVA of transformed AUC values controlling for demographic variables.

### Differences from Original Study and 1st replication

1) Data will be collected on Prolific rather than in person (as in the original study) or on Mechanical Turk (as in the first replication attempt). This is unlikely to make a difference to the results because this is a survey study.

2) The original study's participants were Hong Kong Chinese adults living in Hong Kong, whereas the first replication attempt sampled residents of the United States of any ethnicity. Rather than recruiting participants who live in a specific country, I will recruit participants who identify as Asian and/or list a Chinese language (e.g., Mandarin, Cantonese) as their first language to attempt to sample people with a relatively similar cultural background to the original study's participants. If cultural differences were indeed implicated in the failure to replicate, this strategy may increase the chances of replicating the original study's findings.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

1) Load relevant libraries
2) Write function to compute hyperbolic function
3) Write function to compute RMSE
4) Import data
5) Remove identifying information and extraneous variables
6) Group participants based on age (create an 'age group' column where participants are listed as either 'younger' or 'older')
7) For each age × donation form × kinship cell, fit hyperbolic discount function (i.e., Equation 1) to group median values over seven social distances (N = 1, 2, 5, 10, 20, 50, and 100)
8) Check goodness of fit using R-square and RMSE
9) Fit hyperbolic discount function to individual data and calculate k and AUC values for each participant in each condition
10) Exclude participants whose data does not fit hyperbolic discount function
11) Normalise individual k and AUC values via natural log transformation
12) Exclude individuals with transformed values that exceed ±3 SDs
13) Correlational analyses on demographic variables and transformed individual k/AUC values

```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Results of control measures

1) Exclude participants who failed attention check

### Confirmatory analysis

1) 2 (age: younger vs older) × 2 (donation form: money vs time) × 2 (kinship: relatives vs non-relatives) mixed design, repeated measures ANOVA of transformed individual AUC values, with demographic variables as control + post-hoc tests if applicable
2) 2 (age: younger vs older) × 2 (donation form: money vs time) × 2 (kinship: relatives vs non-relatives) mixed design, repeated measures ANOVA of transformed individual AUC values, without demographic variables as control + post-hoc tests if applicable
3) 2 (age: younger vs older) × 2 (donation form: money vs time) × 2 (kinship: relatives vs non-relatives) mixed design, repeated measures ANOVA of transformed individual k values, with demographic variables as control + post-hoc tests if applicable
4) 2 (age: younger vs older) × 2 (donation form: money vs time) × 2 (kinship: relatives vs non-relatives) mixed design, repeated measures ANOVA of transformed individual k values, without demographic variables as control + post-hoc tests if applicable

*Three-panel graph with original, 1st replication, and your replication is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

## Mini meta analysis
Combining across the original paper, 1st replication, and 2nd replication, what is the aggregate effect size? 

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.